### ISSUE TITLE
Data is not refreshed when mutating

### ISSUE THREAD

**Issue by Newbie012** [Danilo-Zekovic/react-tableql#62]
**Describe the bug**
Upon receiving new data, the table does not update the data.

**Package version**
`react-tableql` version `^0.2.0`. 

**To Reproduce**

Given the following code:

```ts
const GET_ADVERTISERS = gql`
  query GetAdvertisers {
    advertisers(orderBy: { id: asc }, take: 3) {
      id
      name
      isActive
      createdAt
      updatedAt
    }
  }
`

const AdvertisersTable = (props: Props) => {
  const { data, error, loading } = useQuery(GET_ADVERTISERS);

  return (
    <>
      {loading && <Loader />}
      {error && <span>{error}</span>}
      {data && <TableQL data={data.advertisers} onRowClick={props.onClickRow} debug={true} />}
    </>
  );
};
```

The debug prints the following console.log (which is ok):

![image](https://user-images.githubusercontent.com/10504365/110495916-a77cfe80-80fd-11eb-9a87-eeec60dc5752.png)

When I execute a mutation in a different component, it looks like the `data` inside `AdvertisersTable` is updated, and so is `TableQL`, but it looks like it still renders the old value. See this output:

![image](https://user-images.githubusercontent.com/10504365/110496339-0e021c80-80fe-11eb-90e9-58cd3cf3fc4c.png)

(I have changed `isActive` from `true` to `false`).

**Expected behavior**

The array that is returned with the console log `Data to be displayed (array)` should show the updated values.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Danilo-Zekovic** [comment]
Thanks for submitting the issue. I am working on reproducing it and creating the fix. If I have any additional questions I will let you know.

**Comment by Newbie012** [comment]
Hey @Danilo-Zekovic , were you able to reproduce this issue?

**Comment by Danilo-Zekovic** [comment]
Hey, @Newbie012, I was able to reproduce it. I believe I have the fix for. It should be published today after I test the solution. Thank you for your patience.

**Comment by Newbie012** [comment]
Sure thing. Thanks for an amazing library :)

**Comment by Danilo-Zekovic** [comment]
@Newbie012 bug fix is released. Install v0.2.1. of react-tableql and let me know does that fixes your issue. 🤞

**Comment by Newbie012** [comment]
Amazing. Thanks 😊

**Comment by Newbie012** [comment]
Sorry, it looks like it still doesn't work. I have updated to version 0.2.1:

![image](https://user-images.githubusercontent.com/10504365/111221637-6d22ce00-85e3-11eb-8670-24167a3a11c0.png)

**Comment by Danilo-Zekovic** [comment]
I added a new log (in v0.2.1), that should print out something like `Data or columns changed: ` and then the data that you fetched. Does it show at all in the console logs?

**Comment by Newbie012** [comment]
Looks like it was all about re-running `npm start` again. Thanks!
